config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'pages#home'
  
  get '/' => 'pages#home'
  #get '/search', to: 'pages#search'
  get '/stocks/search', to: 'stocks#search', as: :stock_search
  
  get '/orders' => 'pages#orders'
  get '/update_stock', to: 'pages#update_stocks', as: 'updated_stocks'
  get '/userlist', to: 'users#userlist'
  get '/transactions', to: 'users#transactions'

  resources :stocks
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   
  delete '/users/sign_out', to: 'users/sessions#destroy'
  
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :portfolios, through: :trader_stocks
    has_many :trader_stocks
    has_many :orders
  
    def update_stock_quantity order_quantity
      update(quantity: quantity + order_quantity)
    end
  
    def update_existing_stock_price
      update(price: price)
    end
  
    def import_update
      Stocks::Import.new(self).call if ticker.present?
    end
end

app/controllers/stocks_controller.rb
# class StocksController < ApplicationController
#   before_action :set_stock, only: %i[ show edit update destroy ]
# class StocksController < ApplicationController
#   before_action :set_stock, only:rta
#   before_action :set_client, only: %i[update_stocks create_order]

#   # GET /stocks
#   def index
#     @stocks = Stock.all
#   end

#   # GET /stocks/1
#   def show
#   end

#   # GET /stocks/new
#   def new
#     @stock = Stock.new
#   end

#   # GET /stocks/1/edit
#   def edit
#   end

#   # POST /stocks
#   def create
#     @stock = Stock.new(stock_params)

#     if @stock.save
#       redirect_to @stock, notice: "Stock was successfully created."
#     else
#       render :new, status: :unprocessable_entity
#     end
#   end

#   # PATCH/PUT /stocks/1
#   def update
#     if @stock.update(stock_params)
#       redirect_to @stock, notice: "Stock was successfully updated.", status: :see_other
#     else
#       render :edit, status: :unprocessable_entity
#     end
#   end

#   # DELETE /stocks/1
#   def destroy
#     @stock.destroy!
#     redirect_to stocks_url, notice: "Stock was successfully destroyed.", status: :see_other
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_stock
#       @stock = Stock.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     def stock_params
#       params.fetch(:stock, {})
#     end
# end

class StocksController < ApplicationController
  before_action :set_stock, only: %i[show edit update destroy]
  before_action :set_client, only: %i[update_stocks create_order]

  # GET /stocks
  def index
    @stocks = Stock.all
    @orders = Order.all
  end

  # GET /stocks/1
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  def create_stock
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to @stock, notice: "Stock was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /stocks/1
  def update
    if @stock.update(stock_params)
      redirect_to @stock, notice: "Stock was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /stocks/1
  def destroy
    @stock.destroy!
    redirect_to stocks_url, notice: "Stock was successfully destroyed.", status: :see_other
  end

  # POST /orders
  def create_order
    @stock = Stock.find_by(symbol: order_params[:symbol])
    @trader_stocks = TraderStock.where(user_id: current_user.id)
    @order = Order.new(order_params)

    if @order.save
      handle_order_transaction
      redirect_to root_path, notice: "Order was successful."
    else
      redirect_to root_path(user_id: current_user.id, symbol: @stock.symbol), alert: "Order was unsuccessful."
    end
  end

  def update_stocks
    @stocks = Stock.all
    @stocks.each do |stock|
      stock_data = @client.fetch_stock_data(stock.symbol)
      if stock_data
        Rails.logger.info "Fetched data for #{stock.symbol}: #{stock_data.inspect}"
        if stock_data['Meta Data']
          stock.update(
            open: stock_data['Time Series (Daily)'].values.first['1. open'],
            high: stock_data['Time Series (Daily)'].values.first['2. high'],
            low: stock_data['Time Series (Daily)'].values.first['3. low'],
            close: stock_data['Time Series (Daily)'].values.first['4. close'],
            volume: stock_data['Time Series (Daily)'].values.first['5. volume']
          )
        else
          Rails.logger.error "Invalid data structure for #{stock.symbol}: #{stock_data.inspect}"
        end
      else
        Rails.logger.error "Failed to fetch stock data for #{stock.symbol}"
      end
    end
    redirect_to root_path, notice: "Stocks updated successfully."
  rescue StandardError => e
    Rails.logger.error "Exception: #{e.message}"
    redirect_to root_path, alert: "Failed to update stocks: #{e.message}"
  end
  

  private

  def set_stock
    @stock = Stock.find(params[:id])
  end

  def set_client
    @client ||= AlphavantageService.new(ENV['ALPHAVANTAGE_API_KEY'])
  end

  def stock_params
    params.require(:stock).permit(:company_name, :symbol, :logo, :price, :quantity)
  end

  def order_params
    params.require(:order).permit(:order_type, :price, :quantity, :symbol, :user_id)
  end

  def handle_order_transaction
    order_price = @order.order_type == "BUY" ? -(@order.price * @order.quantity) : @order.price * @order.quantity
    order_quantity = @order.order_type == "BUY" ? @order.quantity : -@order.quantity

    if @order.order_type == "BUY"
      handle_buy_order(order_quantity)
    else
      handle_sell_order(order_quantity)
    end

    current_user.recalculate_balance(order_price)
    @stock.update_stock_quantity(order_quantity)
  end

  def handle_buy_order(order_quantity)
    if @trader_stocks.exists?(symbol: @order.symbol)
      @trader_stock = @trader_stocks.find_by(symbol: @order.symbol)
      @trader_stock.add_to_quantity_of_existing_trader_stock(@order.quantity)
    else
      TraderStock.create(
        user_id: order_params[:user_id],
        symbol: order_params[:symbol],
        price: order_params[:price],
        quantity: order_params[:quantity]
      )
    end
  end

  def handle_sell_order(order_quantity)
    @trader_stock = @trader_stocks.find_by(symbol: @order.symbol)
    @trader_stock.update_trader_stock_quantity_when_sell(order_quantity)
    @trader_stock.destroy if @trader_stock.quantity.zero?
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock, class: "contents") do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
</div>

app/views/stocks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing stock</h1>

  <%= render "form", stock: @stock %>

  <%= link_to "Show this stock", @stock, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to stocks", stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/stocks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Stocks" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Stocks</h1>
    <%# <%= link_to "New stock", new_stock_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %> %>
  </div>

  <div id="stocks" class="min-w-full">
    <% @stocks.each do |stock| %>
      <%= render stock %>
      <p>
        <%= link_to "Show this stock", stock, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/stocks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New stock</h1>

  <%= render "form", stock: @stock %>

  <%= link_to "Back to stocks", stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %> 
</div>

app/views/stocks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @stock %>

    <%= link_to "Edit this stock", edit_stock_path(@stock), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to stocks", stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this stock", @stock, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>